header_pages:
 - index.md
 - about.md
theme: minima
title: "Unprompted"
description: "In an age of prompting, hear me Unprompted. Thoughts on product, people, purpose and the spaces in between."
show_excerpts: true
author: "Samriddhi Simlai"
plugins:
 - jekyll-feed
 - jekyll-seo-tag

future: true
