theme: minima
title: "Unprompted"
description: "In an age of prompting, hear me Unprompted. Thoughts on product, people, purpose and the spaces in between."
show_excerpts: true
header_pages:
  - about.md
author:
  name: "Samriddhi Simlai"
